name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main   # 👈 change if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build, tag, and push docker image
      - name: Build, Tag, and Push image to Amazon ECR
        run: |
          IMAGE_TAG=latest
          ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
          REGION=${{ secrets.AWS_REGION }}
          REPO_NAME=orders-service   # 👈 change to your ECR repo name

          echo "Building Docker image..."
          docker build -t 824368189413.dkr.ecr.us-east-1.amazonaws.com/orders-service:$IMAGE_TAG .

          echo "Pushing to ECR..."
          docker push 824368189413.dkr.ecr.us-east-1.amazonaws.com/orders-service:$IMAGE_TAG

      # (Optional) Verify image pushed
      - name: Verify ECR image
        run: |
          ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
          REGION=${{ secrets.AWS_REGION }}
          REPO_NAME=orders-service

          aws ecr describe-images --repository-name $REPO_NAME --region $REGION
